import type { Metadata } from "next";
import GlobalApiProvider from "@/utils/GlobalApiProvider";
import { Inter } from "next/font/google";
import "./globals.css";

// Data Fetching
import ApiFetchCart from "@/api/ApiFetchWeather";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<GlobalApiProvider>
					<ApiFetchCart/>
					{children}
				</GlobalApiProvider>
			</body>
		</html>
	);
}
