import type { Metadata } from "next";
import GlobalApiProvider from "@/utils/GlobalApiProvider";
import { Inter } from "next/font/google";
import "./globals.css";

// Data Fetching
import { ApiFetchClasses } from "@/api/ApiFetchClasses";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "D&D 5E Class Details",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<GlobalApiProvider>
					<ApiFetchClasses />
					{children}
				</GlobalApiProvider>
			</body>
		</html>
	);
}
